### ISSUE TITLE
Mana Innovasion Infograph

### ISSUE THREAD

**Issue by Nasimdisigner** [ManaInnovation/Inotex#7]
[info v2.pptx](https://github.com/ManaInnovation/Inotex/files/14966982/info.v2.pptx)
 
Dear Partner
pls watch this file and preaper your Contant related to its titles

**Comment by Hooman-Tehrani** [comment]
Dear Partner,
I will review the sent file and prepare the content related to its titles.
Thank you.

**Comment by Ali420440** [comment]
> [info v2.pptx](https://github.com/ManaInnovation/Inotex/files/14966982/info.v2.pptx)
> 
> Dear Partner pls watch this file and preaper your Contant related to its titles

very beautiful.good job!!!!

@Nasimdisigner

**Comment by Hooman-Tehrani** [comment]
[20240415 - 1.docx](https://github.com/ManaInnovation/Inotex/files/14975371/20240415.-.1.docx)
Hi everyone,
This is the first draft of the content for the website.
Mrs @ZKermani3m , I wasn't able to find any information about "Among the top 5 European companies' top digital twin initiatives."
It would be fantastic if you could send me a link to any relevant information you might have.
Thanks

**Comment by ZKermani3m** [comment]
https://lnkd.in/ek9Ge4xp

![-2147483648_-210508](https://github.com/ManaInnovation/Inotex/assets/163196445/48fe03de-d57c-474c-bfc2-3570fa625230)

thanks dear Hooman

@Hooman-Tehrani

**Comment by Hooman-Tehrani** [comment]
thanks Mrs @ZKermani3m
